version: "3.7"
services:
  kafka_consumer_php:
    image: anamhossain/php-kafka:latest
    volumes:
      - ./:/var/www/
    environment:
      DB_CONNECTION: mysql
      DB_HOST: kafka_consumer_mysql_db
      DB_PORT: 3306
      KAFKA_BROKERS: kafka:9092
    networks:
      - default
      - proxynet

  kafka_consumer_nginx:
    image: anamhossain/php-nginx:latest
    environment:
      NGINX_ROOT: "/var/www/public"
      NGINX_FPM_HOST: kafka_consumer_php
    ports:
      - 8788:80
    depends_on:
      - kafka_consumer_php
    networks:
      - default
      - proxynet

  kafka_consumer_mysql_db:
    image: mysql:5
    restart: always
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: E8UQxEFic
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3408:3306"
    volumes:
      - "./storage/db-data:/var/lib/mysql"

networks:
  proxynet:
    name: pub_sub_network
    external: true
